angular.module("docstemplates", []).run(["$templateCache", function($templateCache) {$templateCache.put("TEMPLATE_CACHE/component_catalog/component_catalog_tree.html","<div layout=\"column\"><div flex ng-repeat=\"category in m.categories | orderBy: \'name\' \"><div layout=\"row\" flex class=\"md-button-toggle md-button md-default-theme\" ng-click=\"m.toggle_open(category)\">{[{category.name}]} <i ng-hide=\"category.open\" class=\"material-icons\" style=\"font-size: 14px\">keyboard_arrow_down</i> <i ng-show=\"category.open\" class=\"material-icons\" style=\"font-size: 14px\">keyboard_arrow_up</i></div><ul layout=\"column\" ng-show=\"category.open\"><li ng-repeat=\"component in m.components | filter: by_category(category.name) | orderBy: \'name\' \"><a class=\"md-button\" ng-class=\"{\'md-primary\': component == m.active_component}\" href=\"#/{[{component.category}]}/{[{component.title}]}\">{[{component.title}]}</a></li></ul></div></div>");
$templateCache.put("TEMPLATE_CACHE/component_catalog/sample_page.html","<div><md-toolbar layout=\"row\" md-scroll-shrink><div class=\"md-toolbar-tools\"><h1>{[{m.active_component.title}]}</h1><md-button class=\"md-raised\" ng-class=\"{\'md-primary\': m.showing == \'EXAMPLE\'}\" ng-click=\"m.show_example()\">Example</md-button><md-button class=\"md-raised\" ng-class=\"{\'md-primary\': m.showing == \'SOURCE\'}\" ng-click=\"m.show_source()\">View Source</md-button></div></md-toolbar><md-content layout-padding><div ng-if=\"m.showing == \'EXAMPLE\'\" ng-include=\"m.get_include()\"></div><div ng-if=\"m.showing == \'SOURCE\'\"><md-tabs md-border-bottom md-autoselect><md-tab ng-repeat=\"sourcefile in m.active_component.source_files\" label=\"{[{sourcefile.name}]}\"><md-whiteframe class=\"md-whiteframe-z2\" layout layout-padding layout-align=\"left\"><pre>{[{sourcefile.content}]}</pre></md-whiteframe></md-tab></md-tabs></div></md-content></div>");}]);
if(!window.DOCS){
	window.DOCS = {};
}

DOCS.angular_dependencies = [];
DOCS.add_angular_dependency = function(dep){
	DOCS.angular_dependencies.push(dep);
};

angular.module('component_catalog', ['ng_bind_html_unsafe']);
angular.module('component_catalog').factory('ComponentCatalog', function(){
    var catalog = {
        components: []
    };

    catalog.add_test_page = function(options){

        var component = {
            group: options.group,
            title: options.title,
            category: options.category,
            folder: options.folder,
            example: options.example,
            src: options.src,
            source_files: [],
        };
        catalog.components.push(component);
    };

    catalog.get = function(category, title){
        for(var i=0; i<catalog.components.length; i++){
            var component = catalog.components[i];
            if(component.category == category && component.title == title){
                return component;
            }
        }
    };

    function _2array(v){
        return !Array.isArray(v) && v !== undefined ? [v] : v;
    }

    return catalog;
});

angular.module('component_catalog').factory('ComponentCatalogViewModel', function(ComponentCatalog, $http, $templateCache){
    var m = {
        active_component: null,
        showing: 'NOTHING',
        components: [],
        categories: [],
        init: init,
        toggle_open: toggle_open,
        activate: activate,
        show_example: show_example,
        show_source: show_source,
        get_include: get_include,
        get_source: get_source,
    };

    function init(group_filter){
        m.components = ComponentCatalog.components.filter(function(e){
            return e.group == group_filter;
        });
        var catmap = {}
        m.categories = [];
        for(var i=0; i<m.components.length; i++){
            var category = m.components[i].category;
            if(!catmap[category]){
                m.categories.push({name: category});
                catmap[category] = true;
            }
        }
    }

    function toggle_open(category){
        category.open = !category.open;
    }

    function activate(component){
        m.active_component = component;
        m.showing = 'EXAMPLE';
        if(component.source_files.length === 0){
            component.source_files = [{name: component.example}];
            if(component.src){
                component.source_files = component.source_files.concat(component.src.map(function(filename){ return {name: filename}; }));
            }
            function loadfile(sourcefile){
                var url = DOCS.SAMPLE_BASE_URL + component.folder + sourcefile.name;
                $http.get(url).success(function(content){
                    sourcefile.content = content;
                });
            }
            component.source_files.map(loadfile);
        }
        component.active_sourcefile = component.source_files[0];
    }

    function show_example(){
        m.showing = 'EXAMPLE';
    }

    function show_source(){
        m.showing = 'SOURCE';
    }

    function get_include(){
        return DOCS.SAMPLE_BASE_URL + m.active_component.folder + m.active_component.example;
    }

    function get_source(){
        return m.active_component.active_sourcefile.content;
    }

    return m;
})

angular.module('component_catalog').directive('componentCatalogTree', function(ComponentCatalogViewModel){
    return {
        restrict: 'E',
        scope: {
            group: '@'
        },
        templateUrl: DOCS.BASE_URL+'component_catalog/component_catalog_tree.html',
        controller: function($scope) {
            var m = $scope.m = ComponentCatalogViewModel;
            m.init($scope.group);

            $scope.by_category = function(category_name){
                return function(component){
                    return component.category == category_name;
                };
            }
        }
    };
});

angular.module('component_catalog').directive('componentCatalogSample', function(ComponentCatalogViewModel){
    return {
        restrict: 'E',
        scope: {},
        templateUrl: DOCS.BASE_URL+'component_catalog/sample_page.html',
        controller: function($scope) {
            var m = $scope.m = ComponentCatalogViewModel;
        }
    };
});

angular.module('component_catalog').controller('IncludeComponentCatalogSampleCtrl', function($scope, $stateParams, ComponentCatalog, ComponentCatalogViewModel){
    var category = $stateParams.category;
    var title = $stateParams.title;
    var component = ComponentCatalog.get(category, title);
    ComponentCatalogViewModel.activate(component);
});

DOCS.add_angular_dependency('todo');

angular.module('component_catalog').run(function(ComponentCatalog){
    ComponentCatalog.add_test_page({
        group: 'fs',
        title: 'Icon Catalog',
        category: 'Utils',
        folder: 'components/docs/',
        example: 'icon_catalog.html',
        src: ['icon_catalog.js']
    });
});

angular.module('component_catalog').controller('IconCatalogSampleCtrl', function($scope, TODOModel){
    //from https://klarsys.github.io/angular-material-icons/
    $scope.icons = [
        'amazon', 
        'apple', 
        'facebook-box',
        'facebook-messenger',
        'facebook ',
        'github-box ',
        'github-circle ',
        'google-plus-box',
        'google-plus ',
        'hangouts ',
        'linkedin-box ',
        'linkedin',
        'login ',
        'logout ',
        'office ',
        'twitter',
        'whatsapp ',
        'windows',
        '3d_rotation ',
        'accessibility ',
        'account_balance ',
        'account_balance_wallet',
        'account_box ',
        'account_child ',
        'account_circle ',
        'add_shopping_cart',
        'alarm ',
        'alarm_add ',
        'alarm_off ',
        'alarm_on',
        'android ',
        'announcement ',
        'aspect_ratio ',
        'assessment',
        'assignment ',
        'assignment_ind ',
        'assignment_late ',
        'assignment_return',
        'assignment_returned ',
        'assignment_turned_in ',
        'autorenew ',
        'backup',
        'book ',
        'bookmark ',
        'bookmark_outline ',
        'bug_report',
        'cached ',
        'check_circle ',
        'class ',
        'credit_card',
        'dashboard ',
        'delete ',
        'description ',
        'dns',
        'done ',
        'done_all ',
        'event ',
        'exit_to_app',
        'explore ',
        'extension ',
        'face ',
        'favorite',
        'favorite_outline ',
        'find_in_page ',
        'find_replace ',
        'flip_to_back',
        'flip_to_front ',
        'get_app ',
        'grade ',
        'group_work',
        'help ',
        'highlight_remove ',
        'history ',
        'home',
        'https ',
        'info ',
        'info_outline ',
        'input',
        'invert_colors ',
        'label ',
        'label_outline ',
        'language',
        'launch ',
        'list ',
        'lock ',
        'lock_open',
        'lock_outline ',
        'loyalty ',
        'markunread_mailbox ',
        'note_add',
        'open_in_browser ',
        'open_in_new ',
        'open_with ',
        'pageview',
        'payment ',
        'perm_camera_mic ',
        'perm_contact_cal ',
        'perm_data_setting',
        'perm_device_info ',
        'perm_identity ',
        'perm_media ',
        'perm_phone_msg',
        'perm_scan_wifi ',
        'picture_in_picture ',
        'polymer ',
        'print',
        'query_builder ',
        'question_answer ',
        'receipt ',
        'redeem',
        'reorder ',
        'report_problem ',
        'restore ',
        'room',
        'schedule ',
        'search ',
        'settings ',
        'settings_applications',
        'settings_backup_restore ',
        'settings_bluetooth ',
        'settings_cell ',
        'settings_display',
        'settings_ethernet ',
        'settings_input_antenna ',
        'settings_input_component ',
        'settings_input_composite',
        'settings_input_hdmi ',
        'settings_input_svideo ',
        'settings_overscan ',
        'settings_phone',
        'settings_power ',
        'settings_remote ',
        'settings_voice ',
        'shop',
        'shop_two ',
        'shopping_basket ',
        'shopping_cart ',
        'speaker_notes',
        'spellcheck ',
        'star_rate ',
        'stars ',
        'store',
        'subject ',
        'supervisor_account ',
        'swap_horiz ',
        'swap_vert',
        'swap_vert_circle ',
        'system_update_tv ',
        'tab ',
        'tab_unselected',
        'theaters ',
        'thumb_down ',
        'thumb_up ',
        'thumbs_up_down',
        'toc ',
        'today ',
        'track_changes ',
        'translate',
        'trending_down ',
        'trending_neutral ',
        'trending_up ',
        'turned_in',
        'turned_in_not ',
        'verified_user ',
        'view_agenda ',
        'view_array',
        'view_carousel ',
        'view_column ',
        'view_day ',
        'view_headline',
        'view_list ',
        'view_module ',
        'view_quilt ',
        'view_stream',
        'view_week ',
        'visibility ',
        'visibility_off ',
        'wallet_giftcard',
        'wallet_membership ',
        'wallet_travel ',
        'work',
        'error ',
        'warning',
        'album ',
        'av_timer ',
        'closed_caption ',
        'equalizer',
        'explicit ',
        'fast_forward ',
        'fast_rewind ',
        'games',
        'hearing ',
        'high_quality ',
        'loop ',
        'mic',
        'mic_none ',
        'mic_off ',
        'movie ',
        'my_library_add',
        'my_library_books ',
        'my_library_music ',
        'new_releases ',
        'not_interested',
        'pause ',
        'pause_circle_fill ',
        'pause_circle_outline ',
        'play_arrow',
        'play_circle_fill ',
        'play_circle_outline ',
        'play_shopping_bag ',
        'playlist_add',
        'queue ',
        'queue_music ',
        'radio ',
        'recent_actors',
        'repeat ',
        'repeat_one ',
        'replay ',
        'shuffle',
        'skip_next ',
        'skip_previous ',
        'snooze ',
        'stop',
        'subtitles ',
        'surround_sound ',
        'video_collection ',
        'videocam',
        'videocam_off ',
        'volume_down ',
        'volume_mute ',
        'volume_off',
        'volume_up ',
        'web',
        'business ',
        'call ',
        'call_end ',
        'call_made',
        'call_merge ',
        'call_missed ',
        'call_received ',
        'call_split',
        'chat ',
        'clear_all ',
        'comment ',
        'contacts',
        'dialer_sip ',
        'dialpad ',
        'dnd_on ',
        'email',
        'forum ',
        'import_export ',
        'invert_colors_off ',
        'invert_colors_on',
        'live_help ',
        'location_off ',
        'location_on ',
        'message',
        'messenger ',
        'no_sim ',
        'phone ',
        'portable_wifi_off',
        'quick_contacts_dialer ',
        'quick_contacts_mail ',
        'ring_volume ',
        'stay_current_landscape',
        'stay_current_portrait ',
        'stay_primary_landscape ',
        'stay_primary_portrait ',
        'swap_calls',
        'textsms ',
        'voicemail ',
        'vpn_key',
        'add ',
        'add_box ',
        'add_circle ',
        'add_circle_outline',
        'archive ',
        'backspace ',
        'block ',
        'clear',
        'content_copy ',
        'content_cut ',
        'content_paste ',
        'create',
        'drafts ',
        'filter_list ',
        'flag ',
        'forward',
        'gesture ',
        'inbox ',
        'link ',
        'mail',
        'markunread ',
        'redo ',
        'remove ',
        'remove_circle',
        'remove_circle_outline ',
        'reply ',
        'reply_all ',
        'report',
        'save ',
        'select_all ',
        'send ',
        'sort',
        'text_format ',
        'undo',
        'access_alarm ',
        'access_alarms ',
        'access_time ',
        'add_alarm',
        'airplanemode_off ',
        'airplanemode_on ',
        'battery_20 ',
        'battery_30',
        'battery_50 ',
        'battery_60 ',
        'battery_80 ',
        'battery_90',
        'battery_alert ',
        'battery_charging_20 ',
        'battery_charging_30 ',
        'battery_charging_50',
        'battery_charging_60 ',
        'battery_charging_80 ',
        'battery_charging_90 ',
        'battery_charging_full',
        'battery_full ',
        'battery_std ',
        'battery_unknown ',
        'bluetooth',
        'bluetooth_connected ',
        'bluetooth_disabled ',
        'bluetooth_searching ',
        'brightness_auto',
        'brightness_high ',
        'brightness_low ',
        'brightness_medium ',
        'data_usage',
        'developer_mode ',
        'devices ',
        'dvr ',
        'gps_fixed',
        'gps_not_fixed ',
        'gps_off ',
        'location_disabled ',
        'location_searching',
        'multitrack_audio ',
        'network_cell ',
        'network_wifi ',
        'nfc',
        'now_wallpaper ',
        'now_widgets ',
        'screen_lock_landscape ',
        'screen_lock_portrait',
        'screen_lock_rotation ',
        'screen_rotation ',
        'sd_storage ',
        'settings_system_daydream',
        'signal_cellular_0_bar ',
        'signal_cellular_1_bar ',
        'signal_cellular_2_bar ',
        'signal_cellular_3_bar',
        'signal_cellular_4_bar ',
        'signal_cellular_connected_no_internet_0_bar ',
        'signal_cellular_connected_no_internet_1_bar ',
        'signal_cellular_connected_no_internet_2_bar',
        'signal_cellular_connected_no_internet_3_bar ',
        'signal_cellular_connected_no_internet_4_bar ',
        'signal_cellular_no_sim ',
        'signal_cellular_null',
        'signal_cellular_off ',
        'signal_wifi_0_bar ',
        'signal_wifi_1_bar ',
        'signal_wifi_2_bar',
        'signal_wifi_3_bar ',
        'signal_wifi_4_bar ',
        'signal_wifi_off ',
        'storage',
        'usb ',
        'wifi_lock ',
        'wifi_tethering',
        'attach_file ',
        'attach_money ',
        'border_all ',
        'border_bottom',
        'border_clear ',
        'border_color ',
        'border_horizontal ',
        'border_inner',
        'border_left ',
        'border_outer ',
        'border_right ',
        'border_style',
        'border_top ',
        'border_vertical ',
        'format_align_center ',
        'format_align_justify',
        'format_align_left ',
        'format_align_right ',
        'format_bold ',
        'format_clear',
        'format_color_fill ',
        'format_color_reset ',
        'format_color_text ',
        'format_indent_decrease',
        'format_indent_increase ',
        'format_italic ',
        'format_line_spacing ',
        'format_list_bulleted',
        'format_list_numbered ',
        'format_paint ',
        'format_quote ',
        'format_size',
        'format_strikethrough ',
        'format_textdirection_l_to_r ',
        'format_textdirection_r_to_l ',
        'format_underline',
        'functions ',
        'insert_chart ',
        'insert_comment ',
        'insert_drive_file',
        'insert_emoticon ',
        'insert_invitation ',
        'insert_link ',
        'insert_photo',
        'merge_type ',
        'mode_comment ',
        'mode_edit ',
        'publish',
        'vertical_align_bottom ',
        'vertical_align_center ',
        'vertical_align_top ',
        'wrap_text',
        'attachment ',
        'cloud ',
        'cloud_circle ',
        'cloud_done',
        'cloud_download ',
        'cloud_off ',
        'cloud_queue ',
        'cloud_upload',
        'file_download ',
        'file_upload ',
        'folder ',
        'folder_open',
        'folder_shared',
        'cast ',
        'cast_connected ',
        'computer ',
        'desktop_mac',
        'desktop_windows ',
        'dock ',
        'gamepad ',
        'headset',
        'headset_mic ',
        'keyboard ',
        'keyboard_alt ',
        'keyboard_arrow_down',
        'keyboard_arrow_left ',
        'keyboard_arrow_right ',
        'keyboard_arrow_up ',
        'keyboard_backspace',
        'keyboard_capslock ',
        'keyboard_control ',
        'keyboard_hide ',
        'keyboard_return',
        'keyboard_tab ',
        'keyboard_voice ',
        'laptop ',
        'laptop_chromebook',
        'laptop_mac ',
        'laptop_windows ',
        'memory ',
        'mouse',
        'phone_android ',
        'phone_iphone ',
        'phonelink ',
        'phonelink_off',
        'security ',
        'sim_card ',
        'smartphone ',
        'speaker',
        'tablet ',
        'tablet_android ',
        'tablet_mac ',
        'tv',
        'watch',
        'add_to_photos ',
        'adjust ',
        'assistant_photo ',
        'audiotrack',
        'blur_circular ',
        'blur_linear ',
        'blur_off ',
        'blur_on',
        'brightness_1 ',
        'brightness_2 ',
        'brightness_3 ',
        'brightness_4',
        'brightness_5 ',
        'brightness_6 ',
        'brightness_7 ',
        'brush',
        'camera ',
        'camera_alt ',
        'camera_front ',
        'camera_rear',
        'camera_roll ',
        'center_focus_strong ',
        'center_focus_weak ',
        'collections',
        'color_lens ',
        'colorize ',
        'compare ',
        'control_point',
        'control_point_duplicate ',
        'crop_16_9 ',
        'crop ',
        'crop_3_2',
        'crop_5_4 ',
        'crop_7_5 ',
        'crop_din ',
        'crop_free',
        'crop_landscape ',
        'crop_original ',
        'crop_portrait ',
        'crop_square',
        'dehaze ',
        'details ',
        'edit ',
        'exposure',
        'exposure_minus_1 ',
        'exposure_minus_2 ',
        'exposure_plus_1 ',
        'exposure_plus_2',
        'exposure_zero ',
        'filter_1 ',
        'filter ',
        'filter_2',
        'filter_3 ',
        'filter_4 ',
        'filter_5 ',
        'filter_6',
        'filter_7 ',
        'filter_8 ',
        'filter_9 ',
        'filter_9_plus',
        'filter_b_and_w ',
        'filter_center_focus ',
        'filter_drama ',
        'filter_frames',
        'filter_hdr ',
        'filter_none ',
        'filter_tilt_shift ',
        'filter_vintage',
        'flare ',
        'flash_auto ',
        'flash_off ',
        'flash_on',
        'flip ',
        'gradient ',
        'grain ',
        'grid_off',
        'grid_on ',
        'hdr_off ',
        'hdr_on ',
        'hdr_strong',
        'hdr_weak ',
        'healing ',
        'image ',
        'image_aspect_ratio',
        'iso ',
        'landscape ',
        'leak_add ',
        'leak_remove',
        'lens ',
        'looks ',
        'looks_3 ',
        'looks_4',
        'looks_5 ',
        'looks_6 ',
        'looks_one ',
        'looks_two',
        'loupe ',
        'movie_creation ',
        'nature ',
        'nature_people',
        'navigate_before ',
        'navigate_next ',
        'palette ',
        'panorama',
        'panorama_fisheye ',
        'panorama_horizontal ',
        'panorama_vertical ',
        'panorama_wide_angle',
        'photo ',
        'photo_album ',
        'photo_camera ',
        'photo_library',
        'portrait ',
        'remove_red_eye ',
        'rotate_left ',
        'rotate_right',
        'slideshow ',
        'straighten ',
        'style ',
        'switch_camera',
        'switch_video ',
        'tag_faces ',
        'texture ',
        'timelapse',
        'timer_10 ',
        'timer ',
        'timer_3 ',
        'timer_auto',
        'timer_off ',
        'tonality ',
        'transform ',
        'tune',
        'wb_auto ',
        'wb_cloudy ',
        'wb_incandescent ',
        'wb_irradescent',
        'wb_sunny',
        'beenhere ',
        'directions ',
        'directions_bike ',
        'directions_bus',
        'directions_car ',
        'directions_ferry ',
        'directions_subway ',
        'directions_train',
        'directions_transit ',
        'directions_walk ',
        'flight ',
        'hotel',
        'layers ',
        'layers_clear ',
        'local_airport ',
        'local_atm',
        'local_attraction ',
        'local_bar ',
        'local_cafe ',
        'local_car_wash',
        'local_convenience_store ',
        'local_drink ',
        'local_florist ',
        'local_gas_station',
        'local_grocery_store ',
        'local_hospital ',
        'local_hotel ',
        'local_laundry_service',
        'local_library ',
        'local_mall ',
        'local_movies ',
        'local_offer',
        'local_parking ',
        'local_pharmacy ',
        'local_phone ',
        'local_pizza',
        'local_play ',
        'local_post_office ',
        'local_print_shop ',
        'local_restaurant',
        'local_see ',
        'local_shipping ',
        'local_taxi ',
        'location_history',
        'map ',
        'my_location ',
        'navigation ',
        'pin_drop',
        'place ',
        'rate_review ',
        'restaurant_menu ',
        'satellite',
        'store_mall_directory ',
        'terrain ',
        'traffic',
        'apps ',
        'arrow_back ',
        'arrow_drop_down ',
        'arrow_drop_down_circle',
        'arrow_drop_up ',
        'arrow_forward ',
        'cancel ',
        'check',
        'chevron_left ',
        'chevron_right ',
        'close ',
        'expand_less',
        'expand_more ',
        'fullscreen ',
        'fullscreen_exit ',
        'menu',
        'more_horiz ',
        'more_vert ',
        'refresh ',
        'unfold_less',
        'unfold_more',
        'adb ',
        'bluetooth_audio ',
        'disc_full ',
        'dnd_forwardslash',
        'do_not_disturb ',
        'drive_eta ',
        'event_available ',
        'event_busy',
        'event_note ',
        'folder_special ',
        'mms ',
        'more',
        'network_locked ',
        'phone_bluetooth_speaker ',
        'phone_forwarded ',
        'phone_in_talk',
        'phone_locked ',
        'phone_missed ',
        'phone_paused ',
        'play_download',
        'play_install ',
        'sd_card ',
        'sim_card_alert ',
        'sms',
        'sms_failed ',
        'sync ',
        'sync_disabled ',
        'sync_problem',
        'system_update ',
        'tap_and_play ',
        'time_to_leave ',
        'vibration',
        'voice_chat ',
        'vpn_lock',
        'cake ',
        'domain ',
        'group ',
        'group_add',
        'location_city ',
        'mood ',
        'notifications ',
        'notifications_none',
        'notifications_off ',
        'notifications_on ',
        'notifications_paused ',
        'pages',
        'party_mode ',
        'people ',
        'people_outline ',
        'person',
        'person_add ',
        'person_outline ',
        'plus_one ',
        'poll',
        'public ',
        'school ',
        'share ',
        'whatshot',
        'check_box ',
        'check_box_outline_blank ',
        'radio_button_off ',
        'radio_button_on',
        'star ',
        'star_half ',
        'star_outline',
        'live_circle',
    ];
});
DOCS.add_angular_dependency('todo');

angular.module('component_catalog').run(function(ComponentCatalog){
    ComponentCatalog.add_test_page({
        group: 'fs',
        title: 'Example: A TODO',
        category: 'Example',
        folder: 'components/todo_example/docs/',
        example: 'todo_sample.html',
        src: ['todo_sample.js'], //optional
    });
});

angular.module('component_catalog').controller('TodoSampleCtrl', function($scope, TODOModel){
    $scope.add_laundry = function(){
        TODOModel.newtodo = 'Do the laundry';
        TODOModel.add();
    }
});
(function(){

    var deps = [
        'ngMaterial',
        'component_catalog',
        'ui.router',
        'fsngutils',
    ].concat(DOCS.angular_dependencies);
    if(FS.USE_TEAMPLE_CACHE){
        deps.push('fstemplates');
    }
    if(DOCS.USE_TEAMPLE_CACHE){
        deps.push('docstemplates');
    }

    angular.module('docs_main', deps);
    angular.module('docs_main').config(function($interpolateProvider, $controllerProvider, $stateProvider, $urlRouterProvider) {
        $interpolateProvider.startSymbol('{[{').endSymbol('}]}');

        $controllerProvider.allowGlobals();
        $urlRouterProvider.otherwise('/instructions');

        $stateProvider
            .state('base', {
                url: '/:category/:title',
                template: '<component-catalog-sample></component-catalog-sample>',
                controller: 'IncludeComponentCatalogSampleCtrl'
            })
            .state('instructions', {
                url: '/instructions',
                template: '<div layout-padding> select something on the left </div>'
            });
    });
})();
